name: "My Composite Action"
description: "Runs a script and prints a message"
inputs:
  script-path:
    description: "Path to the script to run"
    required: true
    default: "scripts/run.sh"

runs:
  using: "composite"
  steps:
    - name: Print a message
      run: echo "🚀 Running the composite action!"
      shell: bash  


    - name: Run Script
      run: bash ${{ inputs.script-path }}
      shell: bash
